# Generated by Django 5.2.4 on 2025-08-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_name_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', '사용자'), ('bot', '봇'), ('system', '시스템')], max_length=30),
        ),
    ]
