# Generated by Django 5.2.4 on 2025-08-06 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
