# Generated by Django 5.2.4 on 2025-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/", verbose_name="프로필 사진"
            ),
        ),
    ]
