# Generated by Django 5.2.4 on 2025-07-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jembot", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="CustomUser",
        ),
    ]
