# Generated by Django 5.2.4 on 2025-07-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jembot", "0002_rename_user_customuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="Custom_use",
        ),
    ]
