# Generated by Django 5.2.4 on 2025-07-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jembot", "0003_rename_customuser_custom_use"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Custom_use",
            new_name="Custom_user",
        ),
    ]
