# Generated by Django 5.2.4 on 2025-07-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jembot", "0004_rename_custom_use_custom_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nickname",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nickname",
                to="jembot.custom_user",
            ),
        ),
    ]
