# Generated by Django 5.2.4 on 2025-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="google_id",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(max_length=100, verbose_name="사용자 이름"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(max_length=100, unique=True, verbose_name="닉네임"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="프로필 사진",
            ),
        ),
    ]
